- name: catalogue playbook
  become: yes
  hosts: catalogue
  tasks:
  - name: enabling nodejs-20 module
    ansible.builtin.dnf: dnf module enable nodejs:20 -y

  - name: installing nodej
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating system user roboshop
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "Roboshop system user"

  - name: deleting app directory
    ansible.builtin.file:
      name: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download zip file from s3
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: unarchive the zip that is downloaded
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: npm install - installing dependencies
    community.general.npm:
      path: /app
  
  - name: copying the systemctl service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalgoue.service

  - name: copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongo client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
